version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword