server:
  port: 9097

spring:
  application:
    name: ff4j-webconsole-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  flyway:
    url: jdbc:postgresql://localhost:5432/mydb
    user: myuser
    password: mypassword
    locations: classpath:db/migration

redis:
  host: localhost
  port: 6379